#!/usr/bin/env python3
"""Validate the committed Phase 2 static page-analysis package."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from _common import load_json, sha256_file


SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", required=True)
    args = parser.parse_args()
    workspace = Path(args.workspace).expanduser().resolve()
    phase = load_json(workspace / "phase-manifest.json")
    package = workspace / "static-analysis"
    manifest = package / "manifest.sha256"
    committed = package / "COMMITTED"
    errors: list[str] = []
    if phase.get("phase") != 2:
        errors.append("Workspace is not Phase 2")
    if not manifest.is_file() or not committed.is_file():
        errors.append("Static-analysis manifest or COMMITTED marker is missing")
    elif committed.read_text(encoding="utf-8") != sha256_file(manifest) + "\n":
        errors.append("COMMITTED does not bind manifest.sha256")
    else:
        listed: set[str] = set()
        for number, line in enumerate(manifest.read_text(encoding="utf-8").splitlines(), start=1):
            if "  " not in line:
                errors.append(f"Malformed manifest line {number}")
                continue
            digest, name = line.split("  ", 1)
            artifact = package / name
            if not SHA256_RE.fullmatch(digest) or name in listed or "/" in name or "\\" in name:
                errors.append(f"Unsafe or duplicate manifest entry: {name}")
            elif not artifact.is_file() or sha256_file(artifact) != digest:
                errors.append(f"Static-analysis artifact hash mismatch: {name}")
            listed.add(name)
        expected = {
            "project-index.json", "pages.json", "components.json", "events.json", "transitions.json",
            "state-candidates.json", "runtime-tasks.json", "advanced-analysis.json",
            "code-map.candidates.csv", "full-code-candidates.json",
        }
        if listed != expected:
            errors.append("Static-analysis manifest does not exactly cover the required artifacts")
        # Fidelity gate: non-visual tags must not dominate components
        non_visual_count = sum(1 for c in components if c.get("type") in {"layout", "data", "variable", "import"} or c.get("is_visual") is False)
        if non_visual_count > 0:
            errors.append(f"Non-visual components leaked into components.json: {non_visual_count} (filter layout/data/variable)")
        # Visual fidelity: every visual component must have fidelity_attrs
        missing_fidelity = [c for c in components if c.get("is_visual") and not c.get("fidelity_attrs")]
        if missing_fidelity:
            errors.append(f"{len(missing_fidelity)} visual components lack fidelity_attrs (color/size/background)")
        # Project-index must contain asset trace
        if not project_index.get("fidelity_index") or not project_index.get("assets"):
            errors.append("project-index.json missing fidelity_index/assets trace for 1:1 mapping")

    try:
        index = load_json(package / "project-index.json")
        pages = load_json(package / "pages.json").get("pages", [])
        components = load_json(package / "components.json").get("components", [])
        events = load_json(package / "events.json").get("events", [])
        transitions = load_json(package / "transitions.json").get("transitions", [])
        states = load_json(package / "state-candidates.json").get("states", [])
        advanced = load_json(package / "advanced-analysis.json")
        dynamic_risks = advanced.get("dynamic_risks", [])
        side_effects = advanced.get("side_effects", [])
        scenarios = advanced.get("scenarios", [])
        tasks = load_json(package / "runtime-tasks.json").get("tasks", [])
        if index.get("source_revision") != phase.get("source_revision"):
            errors.append("Static analysis is bound to a different source revision")
        if index.get("generated_by") != phase.get("ownership", {}).get("code_map_agent_id"):
            errors.append("Static analysis was not generated by the frozen code-map agent")
        source_scan = index.get("source_scan")
        if not isinstance(source_scan, dict):
            errors.append("Source scan ledger is missing")
        else:
            discovered_count = source_scan.get("discovered_count")
            parsed_count = source_scan.get("parsed_count")
            skipped_count = source_scan.get("skipped_count")
            skipped = source_scan.get("skipped")
            if not all(isinstance(value, int) and value >= 0 for value in (
                discovered_count, parsed_count, skipped_count,
            )):
                errors.append("Source scan ledger counts are invalid")
            elif discovered_count != parsed_count + skipped_count:
                errors.append("Source scan ledger does not conserve discovered files")
            if not isinstance(skipped, list) or len(skipped) != skipped_count:
                errors.append("Source scan skipped-file ledger is inconsistent")
        page_ids = [row.get("page_id") for row in pages]
        component_ids = [row.get("component_id") for row in components]
        event_ids = [row.get("event_id") for row in events]
        transition_ids = [row.get("transition_id") for row in transitions]
        state_ids = [row.get("state_id") for row in states]
        risk_ids = [row.get("risk_id") for row in dynamic_risks]
        effect_ids = [row.get("candidate_id") for row in side_effects]
        scenario_ids = [row.get("scenario_id") for row in scenarios]
        task_ids = [row.get("task_id") for row in tasks]
        if not pages:
            errors.append("Static analysis found no page candidates")
        for label, values in (
            ("Page-ID", page_ids), ("Component-ID", component_ids), ("Event-ID", event_ids),
            ("Transition-ID", transition_ids), ("State-ID", state_ids), ("Task-ID", task_ids),
            ("Dynamic-Risk-ID", risk_ids), ("Side-Effect-ID", effect_ids),
            ("Scenario-ID", scenario_ids),
        ):
            if any(not isinstance(value, str) or not value for value in values) or len(values) != len(set(values)):
                errors.append(f"Missing or duplicate {label}")
        known_pages = set(page_ids)
        if any(row.get("page_id") not in known_pages for row in components):
            errors.append("A component references an unknown page")
        allowed_page_bindings = known_pages | {"PENDING_SOURCE_BINDING"}
        if any(row.get("page_id") not in allowed_page_bindings for row in events):
            errors.append("An event has an invalid source-page binding")
        if any(row.get("page_id") not in allowed_page_bindings for row in states):
            errors.append("A state candidate has an invalid source-page binding")
        if any(row.get("source_page_id") not in allowed_page_bindings for row in transitions):
            errors.append("A transition has an invalid source-page binding")
        page_tasks = {row.get("page_id") for row in tasks if row.get("task_type") == "VERIFY_PAGE_DEFAULT_STATE"}
        if not known_pages.issubset(page_tasks):
            errors.append("Every page candidate must have an automatic default-state verification task")
        required_subjects = (
            set(page_ids) | set(event_ids) | set(transition_ids) | set(state_ids)
            | set(risk_ids) | set(effect_ids) | set(scenario_ids)
        )
        task_subjects = {row.get("subject_id") for row in tasks}
        if not required_subjects.issubset(task_subjects):
            errors.append("Every static and advanced candidate must have a runtime task")
        blocking_gaps = [row for row in tasks if row.get("blocking_discovery_gap") is True]
        if blocking_gaps:
            errors.append(
                "Static analysis contains a blocking discovery gap; fix the source or scanner and recapture"
            )
    except (AttributeError, ValueError) as exc:
        errors.append(str(exc))

    report = {"verdict": "FAIL" if errors else "PASS", "errors": errors}
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
